//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gydymas
    {
        public int Gydymo_Nr { get; set; }
        public System.DateTime Pradeta { get; set; }
        public Nullable<System.DateTime> Baigta { get; set; }
        public string Skirti_Vaistai { get; set; }
        public string GydytojoAK { get; set; }
        public string PacientoAK { get; set; }
        public string Diagnoze { get; set; }
    
        public virtual Gydytojas Gydytojas { get; set; }
        public virtual Pacientas Pacientas { get; set; }
    }
}
