//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gydytojas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gydytojas()
        {
            this.Gydymai = new HashSet<Gydymas>();
        }
    
        public string AK { get; set; }
        public string Vardas { get; set; }
        public string Pavarde { get; set; }
        public string Kvalifikacija { get; set; }
        public decimal Atlyginimas { get; set; }
        public string Ligonine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gydymas> Gydymai { get; set; }
        public virtual Ligonine Ligonine1 { get; set; }
    }
}
