//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligonine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ligonine()
        {
            this.Gydytojai = new HashSet<Gydytojas>();
        }
    
        public string Pavadinimas { get; set; }
        public string Adresas { get; set; }
        public int Biudzetas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gydytojas> Gydytojai { get; set; }
    }
}
