//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LigoninesDBEntities : DbContext
    {
        public LigoninesDBEntities()
            : base("name=LigoninesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gydymas> Gydymas1 { get; set; }
        public virtual DbSet<Gydytojas> Gydytojas1 { get; set; }
        public virtual DbSet<Ligonine> Ligonines { get; set; }
        public virtual DbSet<Pacientas> Pacientas1 { get; set; }
    }
}
